import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeLink from "@/components/home-link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex justify-center items-center min-h-full max-w-sm mx-auto px-3">
        <body className={`${inter.className} w-full`}>
            <HomeLink />
            {children}
        </body>
    </html>
  );
}
